### ISSUE TITLE
Migrations don't seem to migrate

### ISSUE THREAD

**Issue by AsafMah** [webNeat/lumen-generators#2]
I created a resource named Hall, used artisan migrate to migrate, and I get the error "  Class 'CreateHalls' not found  ".
For reference here is the generated CreateHallsMIgration:

``` php
class CreateHallsMigration extends Migration
{

    public function up()
    {
        Schema::create('halls', function(Blueprint $table) {
            $table->increments('id');
            $table->string('name', 100);
            $table->string('email', 255);
            $table->string('phone', 11);
            $table->string('address', 255);
            // Constraints declaration
            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::drop('halls');
    }
}
```

In case it wasn't clear, this was after generating with composer dump-autoload

**Comment by webNeat** [comment]
The error is due to the migration file name. Generated file names for migrations changed to be supported by the `migrate` command ce54fe6d5a34b981df6a1004f310eac9c7b286cc

Please require the dev version on your composer:

```
"wn/lumen-generators": "@dev"
```

then run `composer update` and try again. It should work this time.

These modifications will be available on the next release (1.1.0) that I will make soon.
